apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{ include "api-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      {{ include "api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "api-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
