apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
spec:
  selector: 
    {{- include "api-chart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: webport

